NASM = nasm -felf32
AS = as --32
LD = ld
CC = gcc
CPP = cpp -nostdinc
AR = ar
STRIP = strip
OBJCOPY = objcopy

LDFLAGS = -m elf_i386
CFLAGS  = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce
